workflows:
  dev:
    name: Development Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - dev
    scripts:
      - name: Create .env.dev file
        script: |
          echo "API_URL=$API_URL" > .env.dev
          echo "DEBUG=$DEBUG" >> .env.dev
          echo "API_CONNECT_TIMEOUT=$API_CONNECT_TIMEOUT" >> .env.dev
          echo "API_RECEIVE_TIMEOUT=$API_RECEIVE_TIMEOUT" >> .env.dev
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Generate code
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Generate translation
        script: |
          flutter pub run easy_localization:generate -S assets/translations -f keys -o locale_keys.g.dart
      - name: Generate translation file
        script: |
          flutter pub run easy_localization:generate --source-dir assets/translations
      - name: Build APK
        script: |
          flutter build apk --flavor dev -t lib/main_dev.dart
    #   - name: Build iOS
    #     script: |
    #       flutter build ios --flavor dev -t lib/main_dev.dart
    #   - name: Deploy to TestFlight using Fastlane
    #     script: |
    #       cd ios
    #       fastlane release
    artifacts:
      - app-dev.apk
    #   - build/ios/ipa/*.ipa

  prod:
    name: Production Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - prod
    scripts:
      - name: Create .env.prod file
        script: |
          echo "API_URL=$API_URL" > .env.prod
          echo "DEBUG=$DEBUG" >> .env.prod
          echo "API_CONNECT_TIMEOUT=$API_CONNECT_TIMEOUT" >> .env.prod
          echo "API_RECEIVE_TIMEOUT=$API_RECEIVE_TIMEOUT" >> .env.prod
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Generate code
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
           - name: Generate translation
        script: |
          flutter pub run easy_localization:generate -S assets/translations -f keys -o locale_keys.g.dart
      - name: Generate translation file
        script: |
          flutter pub run easy_localization:generate --source-dir assets/translations
      - name: Build APK
        script: |
          flutter build apk --flavor prod -t lib/main_prod.dart
      - name: Build iOS
        script: |
          flutter build ios --flavor prod -t lib/main_prod.dart
    artifacts:
      - build/app/outputs/flutter-apk/app-prod.apk
      - build/ios/ipa/*.ipa
