workflows:
  dev:
    name: Development Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      env:
        ENV_FILE: .env.dev
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Generate code
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build APK
        script: |
          flutter build apk --flavor dev -t lib/main_dev.dart
      - name: Build iOS
        script: |
          flutter build ios --flavor dev -t lib/main_dev.dart
    artifacts:
      - build/app/outputs/flutter-apk/app-dev.apk
      - build/ios/ipa/*.ipa

  prod:
    name: Production Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      env:
        ENV_FILE: .env.prod
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Generate code
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build APK
        script: |
          flutter build apk --flavor prod -t lib/main_prod.dart
      - name: Build iOS
        script: |
          flutter build ios --flavor prod -t lib/main_prod.dart
    artifacts:
      - build/app/outputs/flutter-apk/app-prod.apk
      - build/ios/ipa/*.ipa
