name: Flutter Build Check

on:
  pull_request:
    branches:
      - "**" # Triggers for all branches

jobs:
  build-check:
    name: Flutter Type and Build Check
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
